name: smarthome
description: Smart Living.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  toggle_switch: ^2.0.1
  esptouch_flutter: ^1.0.0
  firebase_database: ^9.0.15
  firebase_core: ^1.17.1
  get: ^4.6.5
  is_first_run: ^1.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
